### ISSUE TITLE
Can't find the template in VS2019

### ISSUE THREAD

**Issue by NoteToSelfFindGoodNickname** [hurcane/Microsoft.InteropFormTools.InteropFormProxyGenerator#7]
I have copied Source.zip to the following directory:
C:\Users\MyUser\Documents\Visual Studio 2019\Templates\ProjectTemplates\Visual Basic\Source.zip

But I do not see a template when I open up VS2019.

Where should that be located, please?

In this screen?

![183461907-0002981a-57ae-4a1c-a7c5-4d64a22755c5](https://user-images.githubusercontent.com/29504639/183783700-01cb36d8-70c2-447b-9ec0-4c29cdc687e8.png)

**Comment by QiBowen2008** [comment]
Maybe you forgot unzip?

> I have copied Source.zip to the following directory: C:\Users\MyUser\Documents\Visual Studio 2019\Templates\ProjectTemplates\Visual Basic\Source.zip
> 
> But I do not see a template when I open up VS2019.
> 
> Where should that be located, please?
> 
> In this screen?
> 
> ![183461907-0002981a-57ae-4a1c-a7c5-4d64a22755c5](https://user-images.githubusercontent.com/29504639/183783700-01cb36d8-70c2-447b-9ec0-4c29cdc687e8.png)

Maybe you forgot unzip?

**Comment by hurcane** [comment]
I'm sorry, but this VSIX only included the functionality for the Visual Studio AddIn to generate the wrapper classes from within the Visual Studio IDE. I did not include the templates because this was done for work, and we already had the projects created and did not need to convert the templates.

You can view the templates and associated files in the original source code, which comes with the original installer. There really isn't anything special about the templates except that they include a reference to Microsoft.InteropFormTools. You could use one of the standard templates for WinForms (desktop app, control library, etc.), add a reference to Microsoft.InteropFormTools, and you should be ready to go.

You might need to enable the Register for COM Interop property on the project.
